const KEY="cdReservationApp_v1";
const blank={artists:[], cds:[], reservations:[]};
let db=load(), currentPage="home", pageStack=[], selectedCdId=null, editingReservationId=null;

function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(blank)}catch{return structuredClone(blank)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function yen(n){return "¥"+Number(n||0).toLocaleString("ja-JP")}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function artist(id){return db.artists.find(x=>x.id===id)}
function cd(id){return db.cds.find(x=>x.id===id)}
function getPageTitle(){return {home:"CD予約管理",artists:"アーティスト",cds:"CD一覧",reservations:"予約一覧",menu:"メニュー",artistAdd:"アーティスト登録",cdAdd:"CDを追加",cdDetail:"CD詳細",reservationAdd:"予約を追加",reservationDetail:"予約詳細"}[currentPage]||"CD予約管理"}

function nav(page){if(currentPage!==page) pageStack.push(currentPage);currentPage=page;render()}
function back(){if(pageStack.length){currentPage=pageStack.pop();render()}else nav("home")}
function render(){document.getElementById("pageTitle").textContent=getPageTitle();document.getElementById("backBtn").hidden=["home","artists","cds","reservations","menu"].includes(currentPage);document.getElementById("main").innerHTML=pages[currentPage]();document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===currentPage));bindPage()}
document.getElementById("backBtn").onclick=back;document.getElementById("menuBtn").onclick=()=>nav("menu");
document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>{pageStack=[];nav(b.dataset.page)});

const pages=(()=>{
  const P={};
  P.home=()=>`<div class="hero"><h2>好きなCDを、もっと簡単に管理</h2><p>アーティスト・CD・予約・特典をまとめて管理できます。</p></div>
    <div class="grid2"><div class="stat"><strong>${db.cds.length}</strong><span>登録CD</span></div><div class="stat"><strong>${db.reservations.filter(r=>r.status==="reserved").length}</strong><span>予約中</span></div></div>
    <h2 class="section-title">今後の発売予定</h2>${db.cds.filter(c=>new Date(c.releaseDate)>=new Date(new Date().toDateString())).slice(0,5).map(cdCard).join("")||empty("登録されているCDはありません")}
    <button class="primary full" onclick="nav('cdAdd')">＋ CDを登録する</button>
    <h2 class="section-title">よく買うアーティスト</h2><div class="row" style="flex-wrap:wrap">${db.artists.slice(0,8).map(a=>`<button class="secondary" onclick="artistCds('${a.id}')">${esc(a.name)}</button>`).join("")||'<span class="small">まだ登録されていません</span>'}</div>`;
  P.artists=()=>`<div class="search"><input id="artistSearch" placeholder="アーティスト名で検索"></div>
    <div id="artistList">${artistList()}</div><button class="primary full" onclick="nav('artistAdd')">＋ アーティストを追加</button>`;
  P.artistAdd=()=>`<form id="artistForm" class="card"><label>アーティスト名 *</label><input name="name" required placeholder="例：Aぇ! group"><label>メモ（任意）</label><textarea name="memo" placeholder="推しメン・レーベルなど"></textarea><button class="primary full">登録する</button></form>`;
  P.cds=()=>`<div class="search"><input id="cdSearch" placeholder="CDタイトル・アーティストで検索"></div><div class="tabs"><button data-filter="all" class="active">すべて</button><button data-filter="upcoming">発売前</button><button data-filter="released">発売済</button></div><div id="cdList">${cdList()}</div><button class="primary full" onclick="nav('cdAdd')">＋ CDを登録</button>`;
  P.cdAdd=()=>`<form id="cdForm" class="card">
    <label>アーティスト *</label><div class="row"><select name="artistId" required>${db.artists.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("")}</select><button type="button" class="secondary" onclick="nav('artistAdd')">追加</button></div>
    <label>CDタイトル *</label><input name="title" required placeholder="例：○○○○">
    <label>発売日 *</label><input type="date" name="releaseDate" required>
    <label>ジャケット写真</label><button type="button" class="secondary full" id="pickImage">画像を選択</button><div id="preview"></div>
    <label>メモ</label><textarea name="memo"></textarea>
    <div class="form-section"><h3>形態・価格</h3><div id="formatRows">${formatRow()}</div><button type="button" class="secondary full" id="addFormat">＋ 形態を追加</button></div>
    <div class="form-section"><h3>特典設定</h3>
      <label>全形態共通・早期予約特典</label><div class="radio-group"><label class="radio"><input type="radio" name="earlyEnabled" value="yes" checked>あり</label><label class="radio"><input type="radio" name="earlyEnabled" value="no">なし</label></div>
      <label>特典名</label><input name="earlyName" placeholder="例：A3ポスター">
      <label>形態別特典</label><div id="bonusRows"></div>
    </div>
    <button class="primary full">登録する</button></form>`;
  P.cdDetail=()=>{let c=cd(selectedCdId);if(!c)return empty("CDが見つかりません");let a=artist(c.artistId);let sums=cdSummary(c.id);return `<div class="card"><div class="item"><img class="cover large" src="${c.cover||placeholder()}"><div><h2>${esc(c.title)}</h2><p>${esc(a?.name||"")}<br>${c.releaseDate}</p></div></div>
    <h3 class="section-title">形態・価格</h3><table><tr><th>形態</th><th>価格</th></tr>${c.formats.map(f=>`<tr><td>${esc(f.name)}</td><td>${yen(f.price)}</td></tr>`).join("")}</table>
    <h3 class="section-title">特典情報</h3><div class="summary-box"><b>早期予約特典</b><p>${c.earlyBonus?.enabled?esc(c.earlyBonus.name||"あり"):"なし"}</p><b>形態別特典</b>${c.formats.map(f=>`<p>${esc(f.name)}：${esc(f.bonus||"なし")}</p>`).join("")}</div>
    <h3 class="section-title">予約集計</h3><div class="summary-box"><b>形態ごとの予約数</b>${Object.entries(sums.formats).map(([k,v])=>`<div class="summary-line"><span>${esc(k)}</span><strong>${v}枚</strong></div>`).join("")||'<p class="small">まだ予約がありません</p>'}<hr><b>特典ごとの予約数</b>${Object.entries(sums.bonuses).map(([k,v])=>`<div class="summary-line"><span>${esc(k)}</span><strong>${v}件</strong></div>`).join("")||'<p class="small">まだ予約がありません</p>'}<hr><div class="summary-line"><span>未払い金額</span><strong>${yen(sums.unpaid)}</strong></div></div>
    <button class="primary full" onclick="startReservation('${c.id}')">予約する</button></div>`};
  P.reservations=()=>`<div class="search"><input id="reservationSearch" placeholder="CD・アーティストで検索"></div><div class="grid2"><select id="statusFilter"><option value="all">予約状況：すべて</option><option value="reserved">予約済み</option><option value="received">受け取り済み</option></select><select id="paymentFilter"><option value="all">支払い：すべて</option><option value="paid">支払い済み</option><option value="unpaid">未払い</option></select></div><div id="reservationList">${reservationList()}</div>`;
  P.reservationAdd=()=>reservationForm();
  P.reservationDetail=()=>reservationDetail();
  P.menu=()=>`<div class="card menu-list"><button onclick="nav('home')">⌂　ホーム</button><button onclick="nav('cds')">💿　CD一覧</button><button onclick="nav('reservations')">▣　予約一覧</button><button onclick="nav('artists')">♟　アーティスト管理</button><button onclick="nav('cdAdd')">＋　CDを追加</button><button onclick="showData()">⚙　データ確認</button></div><div class="card small">データはこのブラウザのlocalStorageに保存されます。他の端末とは共有されません。</div>`;
  return P;
})();

function empty(t){return `<div class="empty">${t}</div>`}
function placeholder(){return "data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="54%" text-anchor="middle" fill="#aaa" font-size="12">CD</text></svg>`)}
function cdCard(c){let a=artist(c.artistId),s=cdSummary(c.id);return `<div class="card" onclick="openCd('${c.id}')"><div class="item"><img class="cover" src="${c.cover||placeholder()}"><div class="body"><h3>${esc(c.title)}</h3><p>${esc(a?.name||"")} ・ ${c.releaseDate}</p><div><span class="tag">${c.formats.map(f=>`${esc(f.name)} ${s.formats[f.name]||0}`).join(" / ")}</span><span class="tag ${s.unpaid?'red':'green'}">未払い ${yen(s.unpaid)}</span></div></div><span>›</span></div></div>`}
function cdList(filter="all",search=""){let q=search.toLowerCase();return db.cds.filter(c=>{let match=!q||(c.title+" "+(artist(c.artistId)?.name||"")).toLowerCase().includes(q);let date=new Date(c.releaseDate)>=new Date(new Date().toDateString());return match&&(filter==="all"||(filter==="upcoming"&&date)||(filter==="released"&&!date))}).map(cdCard).join("")||empty("該当するCDがありません")}
function artistList(search=""){let q=search.toLowerCase();return db.artists.filter(a=>a.name.toLowerCase().includes(q)).map(a=>`<div class="card item" onclick="artistCds('${a.id}')"><div class="body"><h3>${esc(a.name)}</h3><p>${db.cds.filter(c=>c.artistId===a.id).length}枚のCD</p></div><span>›</span></div>`).join("")||empty("アーティストがいません")}
function formatRow(){return `<div class="format-row"><div class="row"><input name="formatName" placeholder="例：初回限定盤A" required><input name="formatPrice" type="number" min="0" placeholder="価格" required><button type="button" class="remove" onclick="this.closest('.format-row').remove()">×</button></div><label>形態別特典</label><input name="formatBonus" placeholder="例：アクリルキーホルダー（なしの場合は空欄）"></div>`}
function reservationForm(){let c=cd(selectedCdId);if(!c)return empty("CDが選択されていません");let r=editingReservationId?db.reservations.find(x=>x.id===editingReservationId):null;return `<form id="reservationForm" class="card" data-id="${r?.id||""}">
<label>CD</label><div class="item"><img class="cover" src="${c.cover||placeholder()}"><div><b>${esc(c.title)}</b><p>${esc(artist(c.artistId)?.name||"")} / ${c.releaseDate}</p></div></div>
<h3 class="section-title">予約内容</h3><div id="reserveFormats">${c.formats.map(f=>{let x=r?.items?.find(i=>i.formatId===f.id);return `<div class="format-row"><div class="row"><div style="flex:1"><b>${esc(f.name)}</b><p class="small">${yen(f.price)}</p></div><input class="reserveQty" data-format="${f.id}" data-price="${f.price}" type="number" min="0" value="${x?.qty||0}"></div></div>`}).join("")}</div>
<h3 class="section-title">特典</h3><div class="radio-group">${c.earlyBonus?.enabled?`<label class="radio"><input type="radio" name="bonusType" value="early" ${r?.bonusType==="early"||!r?"checked":""}>全形態共通早期予約特典：${esc(c.earlyBonus.name||"")}</label>`:""}<label class="radio"><input type="radio" name="bonusType" value="format" ${r?.bonusType==="format"?"checked":""}>形態別特典</label><label class="radio"><input type="radio" name="bonusType" value="none" ${r?.bonusType==="none"?"checked":""}>特典なし</label></div>
<div id="formatBonusSelect" class="card" style="margin-top:8px;display:${r?.bonusType==="format"?"block":"none"}"><label>形態別特典を選択</label><select name="bonusFormatId">${c.formats.map(f=>`<option value="${f.id}" ${r?.bonusFormatId===f.id?"selected":""}>${esc(f.name)}：${esc(f.bonus||"なし")}</option>`).join("")}</select></div>
<div class="form-section"><h3>予約情報</h3><label>予約店舗</label><input name="store" value="${esc(r?.store||"")}" placeholder="例：タワーレコード"><label>予約方法</label><div class="radio-group"><label class="radio"><input type="radio" name="orderMethod" value="store" ${!r||r.orderMethod==="store"?"checked":""}>店舗</label><label class="radio"><input type="radio" name="orderMethod" value="online" ${r?.orderMethod==="online"?"checked":""}>オンライン</label></div>
<label>受取方法</label><div class="radio-group"><label class="radio"><input type="radio" name="receiveMethod" value="store" ${!r||r.receiveMethod==="store"?"checked":""}>店舗</label><label class="radio"><input type="radio" name="receiveMethod" value="delivery" ${r?.receiveMethod==="delivery"?"checked":""}>配送</label></div>
<label>支払い</label><div class="radio-group"><label class="radio"><input type="radio" name="payment" value="paid" ${!r||r.payment==="paid"?"checked":""}>支払い済み</label><label class="radio"><input type="radio" name="payment" value="unpaid" ${r?.payment==="unpaid"?"checked":""}>店舗で支払い予定</label></div>
<label>送料（かかる場合は金額を入力）</label><div class="row"><label class="radio"><input type="checkbox" id="shippingOn" ${r?.shipping>0?"checked":""}>送料あり</label><input id="shipping" type="number" min="0" value="${r?.shipping||0}" placeholder="送料"></div>
<label>ポイント利用</label><div class="row"><label class="radio"><input type="checkbox" id="pointsOn" ${r?.points>0?"checked":""}>利用する</label><input id="points" type="number" min="0" value="${r?.points||0}" placeholder="利用ポイント"></div>
<label>予約日</label><input type="date" name="date" value="${r?.date||new Date().toISOString().slice(0,10)}"><label>メモ</label><textarea name="memo">${esc(r?.memo||"")}</textarea></div>
<div class="summary-box"><div class="summary-line"><span>商品合計</span><strong id="productTotal">${yen(r?reservationProductTotal(r,c):0)}</strong></div><div class="summary-line"><span>送料</span><strong id="shippingTotal">${yen(r?.shipping||0)}</strong></div><div class="summary-line"><span>ポイント利用</span><strong id="pointsTotal">-${yen(r?.points||0)}</strong></div><div class="total">支払金額 <strong id="grandTotal">${yen(r?reservationGrand(r,c):0)}</strong></div></div>
<button class="primary full">${r?"変更を保存":"予約を登録する"}</button></form>`}
function reservationProductTotal(r,c){return (r.items||[]).reduce((s,i)=>s+(c.formats.find(f=>f.id===i.formatId)?.price||0)*i.qty,0)}
function reservationGrand(r,c){return Math.max(0,reservationProductTotal(r,c)+(r.shipping||0)-(r.points||0))}
function reservationList(){db.reservations=db.reservations.filter(r=>r.status!=="cancelled");let q=(document.getElementById("reservationSearch")?.value||"").toLowerCase(),sf=document.getElementById("statusFilter")?.value||"all",pf=document.getElementById("paymentFilter")?.value||"all";return db.reservations.filter(r=>{let c=cd(r.cdId),a=artist(c?.artistId);let match=!q||((c?.title||"")+" "+(a?.name||"")).toLowerCase().includes(q);return match&&(sf==="all"||r.status===sf)&&(pf==="all"||(pf==="paid"&&r.payment==="paid")||(pf==="unpaid"&&r.payment==="unpaid"))}).map(r=>{let c=cd(r.cdId);return `<div class="card"><div class="item"><img class="cover" src="${c?.cover||placeholder()}"><div class="body"><h3>注文 #${esc(r.orderNo)}　${esc(c?.title||"")}</h3><p>${esc(artist(c?.artistId)?.name||"")} ・ ${r.date}</p><p>${r.items.map(i=>`${esc(c?.formats.find(f=>f.id===i.formatId)?.name||"")} ×${i.qty}`).join(" / ")}</p><span class="tag ${r.status==="received"?"green":""}">${r.status==="received"?"受け取り済み":"予約済み"}</span><span class="tag ${r.payment==="paid"?"green":"red"}">${r.payment==="paid"?"支払い済み":"未払い "+yen(r.unpaid)}</span></div></div><div class="row" style="margin-top:10px"><button class="secondary" onclick="openReservation('${r.id}')">詳細</button>${r.status==="reserved"?`<button class="primary" onclick="confirmReceive('${r.id}')">受け取り完了</button>`:""}</div></div>`}).join("")||empty("該当する予約がありません")}
function reservationDetail(){let r=db.reservations.find(x=>x.id===editingReservationId),c=cd(r?.cdId);if(!r||!c)return empty("予約が見つかりません");return `<div class="card"><div class="item"><img class="cover" src="${c.cover||placeholder()}"><div><h2>注文 #${r.orderNo}</h2><p>${esc(c.title)}<br>${esc(artist(c.artistId)?.name||"")}<br>${r.date}</p></div></div><h3 class="section-title">予約内容</h3>${r.items.map(i=>{let f=c.formats.find(x=>x.id===i.formatId);return `<div class="summary-line"><span>${esc(f?.name||"")} × ${i.qty}</span><strong>${yen((f?.price||0)*i.qty)}</strong></div>`}).join("")}<div class="summary-box"><div class="summary-line"><span>商品合計</span><strong>${yen(reservationProductTotal(r,c))}</strong></div><div class="summary-line"><span>送料</span><strong>${yen(r.shipping)}</strong></div><div class="summary-line"><span>ポイント利用</span><strong>-${yen(r.points)}</strong></div><div class="total">支払金額 <strong>${yen(r.total)}</strong></div></div><h3 class="section-title">特典</h3><p>${esc(bonusLabel(r,c))}</p><p>店舗：${esc(r.store||"未入力")} / ${r.orderMethod==="online"?"オンライン":"店舗"} / ${r.receiveMethod==="delivery"?"配送":"店舗受取"}</p><p>${r.payment==="paid"?"支払い済み":"店舗で支払い予定"}</p><p>状態：${r.status==="received"?"受け取り済み":"予約済み"}</p><div class="row"><button class="secondary" onclick="editReservation('${r.id}')">編集</button><button class="danger" onclick="cancelReservation('${r.id}')">予約を取り消す</button></div></div>`}
function bonusLabel(r,c){if(r.bonusType==="early")return "全形態共通早期予約特典："+(c.earlyBonus?.name||"");if(r.bonusType==="format"){let f=c.formats.find(x=>x.id===r.bonusFormatId);return "形態別特典："+(f?.name||"")+"："+(f?.bonus||"なし")}return "特典なし"}
function cdSummary(cid){let formats={},bonuses={},unpaid=0;db.reservations.filter(r=>r.cdId===cid&&r.status!=="cancelled").forEach(r=>{let c=cd(cid);r.items.forEach(i=>{let f=c.formats.find(x=>x.id===i.formatId);if(f)formats[f.name]=(formats[f.name]||0)+i.qty});bonuses[bonusLabel(r,c)]=(bonuses[bonusLabel(r,c)]||0)+1;if(r.payment==="unpaid")unpaid+=r.unpaid});return{formats,bonuses,unpaid}}
function openCd(id){selectedCdId=id;nav("cdDetail")}
function startReservation(id){selectedCdId=id;editingReservationId=null;nav("reservationAdd")}
function openReservation(id){editingReservationId=id;nav("reservationDetail")}
function editReservation(id){let r=db.reservations.find(x=>x.id===id);selectedCdId=r.cdId;editingReservationId=id;nav("reservationAdd")}
function artistCds(id){pageStack=[];currentPage="cds";setTimeout(()=>{render();document.getElementById("cdSearch").value=artist(id)?.name||"";document.getElementById("cdList").innerHTML=cdList("all",artist(id)?.name||"")},0)}
function confirmReceive(id){showModal("受け取り完了に変更しますか？","この操作を行うと、予約状況が「受け取り済み」に変更されます。よろしいですか？",()=>{let r=db.reservations.find(x=>x.id===id);r.status="received";save();closeModal();render();toast("受け取り済みに変更しました")})}
function cancelReservation(id){showModal("予約を取り消しますか？","この予約を一覧の通常集計から除外します。",()=>{let r=db.reservations.find(x=>x.id===id);r.status="cancelled";save();closeModal();pageStack=[];currentPage="reservations";render();toast("予約を取り消しました")})}
function showModal(title,msg,ok){document.getElementById("modal").innerHTML=`<div class="dialog"><h2>${title}</h2><p class="muted">${msg}</p><div class="dialog-actions"><button class="secondary" onclick="closeModal()">キャンセル</button><button class="primary" id="modalOk">OK</button></div></div>`;document.getElementById("modal").hidden=false;document.getElementById("modalOk").onclick=ok}
function closeModal(){document.getElementById("modal").hidden=true}
function toast(msg){let e=document.createElement("div");e.className="toast";e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
function showData(){showModal("保存データ","このアプリはlocalStorageに保存しています。ブラウザのデータを消去すると登録内容も消えます。",closeModal)}

function bindPage(){
  if(currentPage==="artists"){document.getElementById("artistSearch")?.addEventListener("input",e=>document.getElementById("artistList").innerHTML=artistList(e.target.value))}
  if(currentPage==="cds"){document.getElementById("cdSearch")?.addEventListener("input",e=>document.getElementById("cdList").innerHTML=cdList("all",e.target.value));document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("cdList").innerHTML=cdList(b.dataset.filter,document.getElementById("cdSearch").value)})}
  if(currentPage==="artistAdd")document.getElementById("artistForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);db.artists.push({id:id(),name:f.get("name").trim(),memo:f.get("memo")});save();pageStack=[];nav("artists");toast("アーティストを登録しました")}
  if(currentPage==="cdAdd")bindCdForm();
  if(currentPage==="reservationAdd")bindReservationForm();
  if(currentPage==="reservations"){["reservationSearch","statusFilter","paymentFilter"].forEach(x=>document.getElementById(x)?.addEventListener(x==="reservationSearch"?"input":"change",()=>document.getElementById("reservationList").innerHTML=reservationList()))}
}
function bindCdForm(){
  let form=document.getElementById("cdForm"), cover="";
  document.getElementById("pickImage").onclick=()=>document.getElementById("imagePicker").click();
  document.getElementById("imagePicker").onchange=e=>{let file=e.target.files[0];if(!file)return;let rd=new FileReader();rd.onload=()=>{cover=rd.result;document.getElementById("preview").innerHTML=`<img class="cover large" src="${cover}">`};rd.readAsDataURL(file)};
  document.getElementById("addFormat").onclick=()=>{document.getElementById("formatRows").insertAdjacentHTML("beforeend",formatRow());updateBonusRows()};
  document.getElementById("formatRows").addEventListener("input",updateBonusRows);document.getElementById("formatRows").addEventListener("click",e=>setTimeout(updateBonusRows,0));
  form.onsubmit=e=>{e.preventDefault();let f=new FormData(form), rows=[...document.querySelectorAll("#formatRows .format-row")].map(r=>({id:id(),name:r.querySelector('[name="formatName"]').value.trim(),price:Number(r.querySelector('[name="formatPrice"]').value||0),bonus:r.querySelector('[name="formatBonus"]').value.trim()})).filter(x=>x.name);if(!rows.length){toast("形態を1つ以上登録してください");return}let early=f.get("earlyEnabled")==="yes";db.cds.push({id:id(),artistId:f.get("artistId"),title:f.get("title").trim(),releaseDate:f.get("releaseDate"),cover,memo:f.get("memo"),formats:rows,earlyBonus:{enabled:early,name:early?f.get("earlyName").trim():""}});save();pageStack=[];nav("cds");toast("CDを登録しました")};
  updateBonusRows();
}
function updateBonusRows(){document.getElementById("bonusRows").innerHTML=[...document.querySelectorAll("#formatRows .format-row")].map(r=>{let name=r.querySelector('[name="formatName"]').value||"形態";return `<div class="summary-line"><span>${esc(name)}</span><span>${esc(r.querySelector('[name="formatBonus"]').value||"なし")}</span></div>`}).join("")}
function bindReservationForm(){
  let form=document.getElementById("reservationForm"),c=cd(selectedCdId);
  function calc(){let items=[...document.querySelectorAll(".reserveQty")].map(x=>({formatId:x.dataset.format,qty:Number(x.value||0)})).filter(x=>x.qty>0),pt=items.reduce((s,i)=>s+(c.formats.find(f=>f.id===i.formatId)?.price||0)*i.qty,0),sh=document.getElementById("shippingOn").checked?Number(document.getElementById("shipping").value||0):0,po=document.getElementById("pointsOn").checked?Number(document.getElementById("points").value||0):0;document.getElementById("productTotal").textContent=yen(pt);document.getElementById("shippingTotal").textContent=yen(sh);document.getElementById("pointsTotal").textContent="-"+yen(po);document.getElementById("grandTotal").textContent=yen(Math.max(0,pt+sh-po));return{items,pt,sh,po,total:Math.max(0,pt+sh-po)}}
  document.querySelectorAll(".reserveQty,#shipping,#points").forEach(x=>x.addEventListener("input",calc));document.getElementById("shippingOn").onchange=calc;document.getElementById("pointsOn").onchange=calc;
  document.querySelectorAll('[name="bonusType"]').forEach(x=>x.onchange=()=>document.getElementById("formatBonusSelect").style.display=x.value==="format"?"block":"none");
  form.onsubmit=e=>{e.preventDefault();let f=new FormData(form),v=calc();if(!v.items.length){toast("数量を1つ以上入力してください");return}let r=editingReservationId?db.reservations.find(x=>x.id===editingReservationId):{id:id(),orderNo:String(db.reservations.length+1).padStart(3,"0"),status:"reserved"};r.cdId=c.id;r.items=v.items;r.bonusType=f.get("bonusType")||"none";r.bonusFormatId=f.get("bonusFormatId")||null;r.store=f.get("store").trim();r.orderMethod=f.get("orderMethod");r.receiveMethod=f.get("receiveMethod");r.payment=f.get("payment");r.shipping=v.sh;r.points=v.po;r.total=v.total;r.unpaid=r.payment==="unpaid"?v.total:0;r.date=f.get("date");r.memo=f.get("memo");if(!editingReservationId)db.reservations.push(r);save();pageStack=[];editingReservationId=r.id;currentPage="reservationDetail";render();toast(editingReservationId?"予約を保存しました":"予約を登録しました")};
}
render();
